### ISSUE TITLE
SPIKE: CJ 113 Complaint Response

### ISSUE THREAD

**Issue by UmeshxSolanki** [JudicialAppointmentsCommission/JARS-Team#102]
Reply to Ian Thomson email on formal complaint about expiring ticket.

**Comment by UmeshxSolanki** [comment]
From: Thomson, Ian (JAC) 
Sent: 14 March 2019 11:37
To: Solanki, Umesh <Umesh.Solanki@judicialappointments.gov.uk>; Mangera, Farhana <Farhana.Mangera@Judicialappointments.gov.uk>
Cc: Troughton, Claire <Claire.Troughton@judicialappointments.gov.uk>
Subject: FW: Official: Judicial Appointments Commission independent assessment request for Circuit Judge

**Comment by Farhana-12** [comment]
Email sent by Farhana
