### ISSUE TITLE
115 DJ MC - Digital Support

### ISSUE THREAD

**Issue by UmeshxSolanki** [JudicialAppointmentsCommission/JARS-Team#11]
Copied #222:

 - [ ] Planning meeting checks. Application setup.
 - [ ] Go / no go decision meeting

Chat with Linda, setup meeting with Abdalla on Feb 18th to review the application.

https://waffle.io/JudicialAppointmentsCommission/documentation/cards/5c459be42b69ff043f39d335

**Comment by Farhana-12** [comment]
Farhana attended
