### ISSUE TITLE
Digital Board: Commissioners to be invited to fortnightly “show and tell” meetings as soon as practical

### ISSUE THREAD

**Issue by UmeshxSolanki** [JudicialAppointmentsCommission/JARS-Team#28]
Copied #178:

Description collaborator
On email from Head of Ops on 2nd Nov
 
Farhana-12 commented 2 months ago collaborator
waiting for confirmation from CT

https://waffle.io/JudicialAppointmentsCommission/documentation/cards/5c04f18e9bec4f01010c85ef

**Comment by Farhana-12** [comment]
Spoke to Claire - US will attend Digital Board and can give update on JARS at the meeting
